config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :pictures
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
     before_validation { email.downcase! }
     has_secure_password
     validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
include SessionsHelper
before_action :login_required
private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

    before_action :set_picture, only: [:show, :edit, :update, :destroy]

    def confirm
        # @picture = Picture.new(picture_params)
        # @picture.user_id = current_user.id
        @picture = current_user.pictures.build(picture_params)
        render :new if @picture.invalid?
    end

    def new
        @picture = Picture.new
    end

    def index
        @pictures = Picture.all
    end

    def create
        # @picture = Picture.new(picture_params)
        # @picture.user_id = current_user.id
        @picture = current_user.pictures.build(picture_params)
        if params[:back]
            render :new
        else
          if @picture.save
            redirect_to pictures_path notice: "投稿完了"
        else
            render :new
        end
      end
    end

    def show
        
    end

    def edit
        
    end

    def destroy
        @picture.destroy
        redirect_to pictures_path, notice:"削除しました！"
    end

    def update
        
        if @picture.update(picture_params)
          redirect_to pictures_path, notice: "編集完了！"
        else
          render :edit
        end
    end

    private
    def picture_params
    params.require(:picture).permit(:image, :content,  :image_cach)
    end
    def set_picture
    @picture = Picture.find(params[:id])
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :login_required, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
          else
            render :new
          end
    end

    def show
        @user = User.find(params[:id])
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
          confirm_pictures_path
        elsif action_name == 'edit'
          picture_path
        end
      end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
      def logged_in?
        current_user.present?
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ffkk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
      <ul>
        <li><a href="#">FFKK</a></li>
      </ul>
      </header>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if logged_in? %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
    　　　<%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
    <footer>
      <p>FFKK</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true,url: choose_new_or_edit) do |form| %>
    <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="picture_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="field">
       <%= form.label :image %>
     <%= form.file_field :image %>
    </div>
    <%= form.submit %>
  <% end %>
  <%= link_to "一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @picture.image %></p>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back'%>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿情報</h1>
<p><%= notice %></p>
<table>
  </tr>
<% @pictures.each do |picture| %>
  <ul class="list-group">
    <p><%=picture.image %></P>
    <p><%= picture.content %></p>
    <p><%= picture.user.name%></p>
    <li class="list-group-item"><%= link_to '詳細を確認する', picture_path(picture.id) %></li>
    <li class="list-group-item"><%= link_to "編集する", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' }  %></li>
    <li class="list-group-item"><%= link_to "削除する", picture_path(picture.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></li>
    </ul>
<% end %>
</table>
<%= link_to '新しい投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<h2>作成する</h2>
  <%= render 'form' %>

app/views/pictures/show.html.erb
<h1>詳細画面</h1>
<p><strong>Image:</strong>
<%= image_tag @picture.image.url if @picture.image.present? %></p>
<p>内容: <%= @picture.content %></p>

app/views/users/new.html.erb
<div class="alert alert-success"><h1>Sign up</h1></div>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="fixed-top bg-primary"><%= @user.name %>のページ</div>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to "投稿作成", new_picture_path %>